config/routes.rb
CMS::Application.routes.draw do
  devise_for :views
  devise_for :users
  namespace :admin do 
    resources :posts
    resources :pages
    root to: "posts#index"
    match 'users/:id' => 'users#show' 
    match 'users/' => 'users#index' 
    match 'users/cancel/:id' => 'users#destroy'
    match 'users/elevate/:id' => 'users#elevate'
    match 'users/suppress/:id' => 'users#suppress'
    match 'admins/' => 'users#admins'
  end

  resources :pages, only: [:show]
  match '/posts/all', :controller => 'posts', :action => 'all'
  match '/users/:id' => 'users#show'
  resources :posts, only: [:index, :show, :all]
  root to: "posts#index"

end

app/views/admin/pages/_contentform.html.erb
<div class='span8 well'>
<div class='row-fluid'>
<%= form_for([:admin, @page], html: {multipart: true}) do |f| %>
	<div class='span3'>
		<%= f.label(:title) %>
		<%= f.text_field(:title) %>


	</div>
	<div class='span5 pull-right'>	
		<div class='span5'><%= f.label(:content) %></div>
		<%= f.text_area(:content) %><br>
	<%= f.submit(:class => 'btn btn-primary') %>
	<%= button_tag("Reset", type: :reset, :class => 'btn btn-danger')%>
    </div>
	<% end %>
</div>
</div>

app/views/admin/pages/_form.html.erb
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>New Page</h3>
  </div>
  			<%= form_for([:admin, @page], remote: true) do |f| %>

  <div class="modal-body span10" >
					<%= f.label(:title) %>
					<%= f.text_field(:title,:class=>'span5') %>
					<%= f.label(:content) %>
					<%= f.text_area(:content, :class=>'span5') %>
  </div>

  <div class="modal-footer">
       
        <%= f.submit(:class => 'btn btn-primary') %>
       <button class="btn btn-success" data-dismiss="modal" aria-hidden="true">Close</button>


  </div>
          <% end %>

</div>

app/views/admin/pages/_page.html.erb
	<thead>
		<th>
			Title
		</th>
		<th>
			Created On
		</th>
		<th>

		</th>

	</thead>
	<tbody> 
		<% @pages.each do |page| %>
			<%= content_tag_for( :tr, page) do %>
			<tr>
		
			<%= render :partial => 'page_tool', :locals => {:page => page} %>
    		</tr>
			<% end %>
		<% end %>
	</tbody>

app/views/admin/pages/_page_tool.html.erb
<td>

	<%= page.title %> 
</td>
<td>
	<%= page.created_at.strftime("%Y-%m-%d %H:%M") %> 
</td>
<td>
		<div class='btn-group'>
			<div class='btn btn-primary btn-admin'> 
				<%= link_to('View',admin_page_path(page)) %> 
			</div>
			<div class='btn btn-info btn-admin'>
				<%= link_to('Edit', edit_admin_page_path(page)) %> 
			</div>
			<div class='btn btn-danger btn-admin'>
				<%= link_to("Delete",admin_page_path(page), method: :delete, confirm: "Are you sure?" ) %>
			</div>
		</div>
</td>

app/views/admin/pages/btn.html.erb
        <li>
        </li>
        <li>
          <%= link_to('Create Page', new_admin_page_path) %>

        </li>

app/views/admin/pages/create.js.erb
$("#listing tr:last").after("<tr><%= escape_javascript(render :partial => 'page_tool', :locals => {:page => @page}) %><tr>");
$("#page-modal").modal("hide");

app/views/admin/pages/edit.html.erb
	<legend> 
		Edit Page
	</legend>

<%= render('contentform') %> 

app/views/admin/pages/index.html.erb
<%= stylesheet_link_tag "admin/btn-link" %>
    <%= link_to('Create Page', new_admin_page_path, class: 'btn btn-success btn-large pull-right btn-admin', remote: true) %>
<table class='table table-striped table-condensed' id='listing'>

	<%= render('page') %>
</table>

app/views/admin/pages/new.html.erb
<legend>Create Page</legend>
<%= render('contentform') %>

app/views/admin/pages/new.js.erb
$("#page-modal").html("<%= j render 'form' %>");
$("#page-modal").modal("show");

app/views/admin/pages/show.html.erb
<div style="padding:20px" class="container">
<h1><%= @page.title %> </h1>
<p><%= @page.content %></p>
<p><h2><%= link_to('Index',admin_pages_path) %> </h2>
</p>
</div>