config/routes.rb
CMS::Application.routes.draw do
  devise_for :views
  devise_for :users
  namespace :admin do 
    resources :posts
    resources :pages
    root to: "posts#index"
    match 'users/:id' => 'users#show' 
    match 'users/' => 'users#index' 
    match 'users/cancel/:id' => 'users#destroy'
    match 'users/elevate/:id' => 'users#elevate'
    match 'users/suppress/:id' => 'users#suppress'
    match 'admins/' => 'users#admins'
  end

  resources :pages, only: [:show]
  match '/posts/all', :controller => 'posts', :action => 'all'
  match '/users/:id' => 'users#show'
  resources :posts, only: [:index, :show, :all]
  root to: "posts#index"

end

app/views/layouts/admin/_sidebar.html.erb
<div class='span3'>
	<div class='well sidebar-nav' style='background-color: #E5E4E2'>
		<ul class='nav nav-list'>
				<li class='nav-header'>
					Contents
				</li>

        <li>
          <%= activeable_link_to_li('li','Posts', admin_posts_path) %>
        </li>
        <li>
          <%= activeable_link_to_li('li','Pages', admin_pages_path) %>

        </li>
        <li class='nav-header'>
          Users and Access Control
        </li>
        <li>
          <%= activeable_link_to_li('li','Users', admin_users_path) %>
        </li>
        <li>
          <%= activeable_link_to_li('li','Administrators', admin_admins_path) %>
        </li>

		</ul>
	</div>
</div>

app/views/layouts/admin/base.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CMS - Dashboard</title>
  <%= stylesheet_link_tag "admin/btn-link" %>
  <%= stylesheet_link_tag    "admin/base" %>
  <%= javascript_include_tag "admin" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class='navbar navbar-inverse navbar-fixed-top'>
  <div class='navbar-inner'>
  		<div class ='container-fluid'>
    		<div class='brand btn-admin'>
          <%= link_to("CMS - Dashboard", admin_root_path )%>
        </div>
  	        <%= render_admin_profile %>
  		</div>
  </div>
</div>
<div class='container-fluid'>
	<div class='row-fluid'>
      <%= render('sidebar')%>
  <div class='span8'>	
	 <%= yield %>
  </div>
</div>
<div id='page-modal' class='modal hide fade'></div>
</body>
</html>