config/routes.rb
CMS::Application.routes.draw do
  devise_for :views
  devise_for :users
  namespace :admin do 
    resources :posts
    resources :pages
    root to: "posts#index"
    match 'users/:id' => 'users#show' 
    match 'users/' => 'users#index' 
    match 'users/cancel/:id' => 'users#destroy'
    match 'users/elevate/:id' => 'users#elevate'
    match 'users/suppress/:id' => 'users#suppress'
    match 'admins/' => 'users#admins'
  end

  resources :pages, only: [:show]
  match '/posts/all', :controller => 'posts', :action => 'all'
  match '/users/:id' => 'users#show'
  resources :posts, only: [:index, :show, :all]
  root to: "posts#index"

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :title, :user_id, :icon
  mount_uploader(:icon, IconUploader)
  def creator
  		author = "";
  		if(user_id)
  			creator = User.find(user_id)
  			author = creator.givennames
  		else
  			author = "Staff Writer"
  		end

  		return author
  end
  def age_create
  	currentTime = Time.now
  	return currentTime - created_at
  end
  def age_update	

  end 
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController
	def index 
		@posts = Post.all
	end

	def new
		@post = Post.new
	end
	
	def edit 
		@post = Post.find(params[:id]);
	end
	
	def create
	 @post = Post.new(params[:post])
	 @post.user_id = current_user.id
	 respond_to do |format|
       if @post.save
        format.html { redirect_to(admin_posts_path, :notice => 'Post was successfully created.') }
        format.xml  { render :xml => @post, :status => :created, :location => @post }
       else
        format.html { render :action => "new" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
       end
      end
	end
	def destroy 
		@post = Post.find(params[:id])
		@post.destroy
		respond_to do |format|
    		format.html { redirect_to(admin_posts_path) }
    		format.xml  { head :ok }
  		end
	end
	def update
		@post = Post.find(params[:id])
		@post.user_id = current_user.id
		respond_to do |format|
    		if @post.update_attributes(params[:post])
      			format.html { redirect_to(admin_posts_path, :notice => 'Post was successfully updated.') }
      			format.xml  { head :ok }
    		else
      			format.html { render :action => "edit" }
      			format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
    		end
   		end
  	end
  	def show
		@post = Post.find(params[:id])
	end
	def view
		@post = Post.view
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index(lastPosts = 3)
		@posts = Post.last(lastPosts)
	end
	def all 
		@posts = Post.all
	end
	def show
		@post = Post.find(params[:id])
	end
	def view
		@post = Post.view
	end
	def createComment(pid, uid)
		
		@comment =Comment.new
		@comment.user_id =  @post.user_id
		@comment.post_id = @post.id
	end
end

app/helpers/posts_helper.rb
module PostsHelper
	def post_cover
		if post.icon 
			image_tag(post.icon)
		else
			"nill"
		end
	end
end

app/views/admin/posts/_contentform.html.erb
<div class='span8 well'>
<div class='row-fluid'>
<%= form_for([:admin, @post], html: {multipart: true}) do |f| %>
	<div class='span3'>
		<%= f.label(:title) %>

		<%= f.text_field(:title) %>

		<%= f.label(:icon) %>

		<%= f.file_field(:icon) %> 
	</div>
	<div class='span5 pull-right'>	
		<div class='span5'><%= f.label(:content) %></div>
		<%= f.text_area(:content) %><br>
	<%= f.submit(:class => 'btn btn-primary') %>
	<%= button_tag("Reset", type: :reset, :class => 'btn btn-danger')%>
    </div>
	<% end %>
</div>
</div>

app/views/admin/posts/edit.html.erb
	<legend> 
		Edit Post
	</legend>
<%= render('contentform') %> 

app/views/admin/posts/index.html.erb
<%= stylesheet_link_tag "admin/btn-link" %>
<div class= 'btn btn-success btn-large pull-right btn-admin'>
<%= link_to('Create Post', new_admin_post_path) %>
</div>
<table class='table table-striped table-condensed'>
	<thead>
		<th>
			Title
		</th>
		<th>
			Created On
		</th>
		<th>

		</th>

	</thead>

<% @posts.each do |post| %>
	<tbody>
		<tr>
		<td>
			<%= post.title %> 
		</td>
		<td>
	 		<%= post.created_at.strftime("%Y-%m-%d %H:%M") %> 
		</td>
		<td>
			<div class='btn-group'>
				<div class='btn btn-primary btn-admin'> 
					<%= link_to('View',admin_post_path(post)) %> 
				</div>
				<div class='btn btn-info btn-admin'>
					<%= link_to('Edit', edit_admin_post_path(post)) %> 
				</div>
				<div class='btn btn-danger btn-admin'>
					<%= link_to("Delete",admin_post_path(post), method: :delete, confirm: "Are you sure?" ) %>
				</div>
			</div>
		</td>
    	</tr>

	</tbody>
	<% end %>

</table>

app/views/admin/posts/new.html.erb
<legend>Create Post</legend>
<%= render('contentform') %>

app/views/admin/posts/show.html.erb
<div style="padding:20px" class="container">
<h1><%= @post.title %> </h1>
<p><%= @post.content %></p>
<p><h2><%= link_to('Index',admin_posts_path) %> </h2>
</p>
</div>