config/routes.rb
CMS::Application.routes.draw do
  devise_for :views
  devise_for :users
  namespace :admin do 
    resources :posts
    resources :pages
    root to: "posts#index"
    match 'users/:id' => 'users#show' 
    match 'users/' => 'users#index' 
    match 'users/cancel/:id' => 'users#destroy'
    match 'users/elevate/:id' => 'users#elevate'
    match 'users/suppress/:id' => 'users#suppress'
    match 'admins/' => 'users#admins'
  end

  resources :pages, only: [:show]
  match '/posts/all', :controller => 'posts', :action => 'all'
  match '/users/:id' => 'users#show'
  resources :posts, only: [:index, :show, :all]
  root to: "posts#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CMS</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
    <link href="../assets/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
    <link rel="shortcut icon" href="../assets/ico/favicon.png">
</head>
<body>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
     <a class="brand">CMS</a>
     <div class="nav-collapse collapse">
      <ul class="nav">
       <li><%= activeable_link_to_li(:li,"Home", root_path)%></li>
       <li><%= activeable_link_to_li(:li,"Blog", posts_all_path) %></li>
      </ul>
      </div>
      <div class="pull-right navbar-text">
        <%= render_user_profile %>
      </div>
    </div>
  </div>
</div>
<div class="container">
    <%= yield %>
<HR/>
<footer>
 <strong>Demo Site for Internal User Only</strong>
</footer>
</div>

    <script src="../assets/js/jquery.js"></script>
    <script src="../assets/js/bootstrap-transition.js"></script>
    <script src="../assets/js/bootstrap-alert.js"></script>
    <script src="../assets/js/bootstrap-modal.js"></script>
    <script src="../assets/js/bootstrap-dropdown.js"></script>
    <script src="../assets/js/bootstrap-scrollspy.js"></script>
    <script src="../assets/js/bootstrap-tab.js"></script>
    <script src="../assets/js/bootstrap-tooltip.js"></script>
    <script src="../assets/js/bootstrap-popover.js"></script>
    <script src="../assets/js/bootstrap-button.js"></script>
    <script src="../assets/js/bootstrap-collapse.js"></script>
    <script src="../assets/js/bootstrap-carousel.js"></script>
    <script src="../assets/js/bootstrap-typeahead.js"></script>

</body>
</html>